// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	 int N = Integer.parseInt(args[0]);
	 double ratio=0;
	 int count1 = 0;
	 int count2 = 0;
	 for (int i=0; i < N; i++) {
		double current = Math.random();
		if(current > 0.5) {
			count1+=1;
		}
		else {
			count2+=1;
		}
	 }
	 if (count1 == 0 || count2 ==0) {
		System.out.println("> 0.5: "+count1);
		System.out.println("<= 0.5: "+count2);

	 }
	 else {
		System.out.println("> 0.5: "+count1);
		System.out.println("<= 0.5: "+count2);
		System.out.println( (double)count1 / count2);
	 }


	 
	 


	}
}
